find_path(SNAPPY_INCLUDE_DIR snappy.h ${CONAN_INCLUDE_DIRS_SNAPPY})
find_library(SNAPPY_LIBRARY NAMES ${CONAN_LIBS_SNAPPY} PATHS ${CONAN_LIB_DIRS_SNAPPY})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(SNAPPY DEFAULT_MSG SNAPPY_INCLUDE_DIR SNAPPY_LIBRARY)

if(SNAPPY_FOUND)
    set(SNAPPY_LIBRARIES ${SNAPPY_LIBRARY})
    set(SNAPPY_INCLUDE_DIRS ${SNAPPY_INCLUDE_DIR})
endif()
