find_path(ZSTD_INCLUDE_DIR zstd.h ${CONAN_INCLUDE_DIRS_ZSTD})
find_library(ZSTD_LIBRARY NAMES ${CONAN_LIBS_ZSTD} PATHS ${CONAN_LIB_DIRS_ZSTD})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(ZSTD DEFAULT_MSG ZSTD_INCLUDE_DIR ZSTD_LIBRARY)

if(ZSTD_FOUND)
    set(ZSTD_LIBRARIES ${ZSTD_LIBRARY})
    set(ZSTD_INCLUDE_DIRS ${ZSTD_INCLUDE_DIR})
endif()
