find_path(HDR_HISTOGRAM_INCLUDE_DIR hdr_histogram/hdr_histogram.h ${CONAN_INCLUDE_DIRS_HDR_HISTOGRAM})
find_library(HDR_HISTOGRAM_LIBRARY NAMES ${CONAN_LIBS_HDR_HISTOGRAM} PATHS ${CONAN_LIB_DIRS_HDR_HISTOGRAM})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(HDR_HISTOGRAM DEFAULT_MSG HDR_HISTOGRAM_INCLUDE_DIR HDR_HISTOGRAM_LIBRARY)

if(HDR_HISTOGRAM_FOUND)
    set(HDR_HISTOGRAM_LIBRARIES ${HDR_HISTOGRAM_LIBRARY})
    set(HDR_HISTOGRAM_INCLUDE_DIRS ${HDR_HISTOGRAM_INCLUDE_DIR})
endif()
