find_path(ROCKSDB_INCLUDE_DIR rocksdb/c.h ${CONAN_INCLUDE_DIRS_ROCKSDB})
find_library(ROCKSDB_LIBRARY NAMES ${CONAN_LIBS_ROCKSDB} PATHS ${CONAN_LIB_DIRS_ROCKSDB})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(ROCKSDB DEFAULT_MSG ROCKSDB_INCLUDE_DIR ROCKSDB_LIBRARY)

if(ROCKSDB_FOUND)
    set(ROCKSDB_LIBRARIES ${ROCKSDB_LIBRARY})
    set(ROCKSDB_INCLUDE_DIRS ${ROCKSDB_INCLUDE_DIR})
endif()
