find_path(JAEGERTRACING_INCLUDE_DIR jaegertracing/Tracer.h ${CONAN_INCLUDE_DIRS_JAEGER-CLIENT-CPP})
find_library(JAEGERTRACING_LIBRARY NAMES ${CONAN_LIBS_JAEGER-CLIENT-CPP} PATHS ${CONAN_LIB_DIRS_JAEGER-CLIENT-CPP})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(JAEGERTRACING DEFAULT_MSG JAEGERTRACING_INCLUDE_DIR JAEGERTRACING_LIBRARY)

if(JAEGERTRACING_FOUND)
    set(JAEGERTRACING_LIBRARIES ${JAEGERTRACING_LIBRARY})
    set(JAEGERTRACING_INCLUDE_DIRS ${JAEGERTRACING_INCLUDE_DIR})
endif()
