find_path(CRYPTOPP_INCLUDE_DIR cryptopp/cryptlib.h ${CONAN_INCLUDE_DIRS_CRYPTOPP})
find_library(CRYPTOPP_LIBRARY NAMES ${CONAN_LIBS_CRYPTOPP} PATHS ${CONAN_LIB_DIRS_CRYPTOPP})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(CRYPTOPP DEFAULT_MSG CRYPTOPP_INCLUDE_DIR CRYPTOPP_LIBRARY)

if(CRYPTOPP_FOUND)
    set(CRYPTOPP_LIBRARIES ${CRYPTOPP_LIBRARY})
    set(CRYPTOPP_INCLUDE_DIRS ${CRYPTOPP_INCLUDE_DIR})
endif()
