find_path(LOG4CPLUS_INCLUDE_DIR log4cplus/logger.h ${CONAN_INCLUDE_DIRS_LOG4CPLUS})
find_library(LOG4CPLUS_LIBRARY NAMES ${CONAN_LIBS_LOG4CPLUS} PATHS ${CONAN_LIB_DIRS_LOG4CPLUS})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(LOG4CPLUS DEFAULT_MSG LOG4CPLUS_INCLUDE_DIR LOG4CPLUS_LIBRARY)

if(LOG4CPLUS_FOUND)
    set(LOG4CPLUS_LIBRARIES ${LOG4CPLUS_LIBRARY})
    set(LOG4CPLUS_INCLUDE_DIRS ${LOG4CPLUS_INCLUDE_DIR})
endif()
