find_path(YAML-CPP_INCLUDE_DIR yaml-cpp/yaml.h ${CONAN_INCLUDE_DIRS_YAML-CPP})
find_library(YAML-CPP_LIBRARY NAMES ${CONAN_LIBS_YAML-CPP} PATHS ${CONAN_LIB_DIRS_YAML-CPP})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(YAML-CPP DEFAULT_MSG YAML-CPP_INCLUDE_DIR YAML-CPP_LIBRARY)

if(YAML-CPP_FOUND)
    set(YAML-CPP_LIBRARIES ${YAML-CPP_LIBRARY})
    set(YAML-CPP_INCLUDE_DIRS ${YAML-CPP_INCLUDE_DIR})
endif()
