find_path(BZIP2_INCLUDE_DIR bzlib.h ${CONAN_INCLUDE_DIRS_BZIP2})
find_library(BZIP2_LIBRARY NAMES ${CONAN_LIBS_BZIP2} PATHS ${CONAN_LIB_DIRS_BZIP2})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(BZIP2 DEFAULT_MSG BZIP2_INCLUDE_DIR BZIP2_LIBRARY)

if(BZIP2_FOUND)
    set(BZIP2_LIBRARIES ${BZIP2_LIBRARY})
    set(BZIP2_INCLUDE_DIRS ${BZIP2_INCLUDE_DIR})
endif()
