find_path(OPENTRACING_INCLUDE_DIR opentracing/tracer.h ${CONAN_INCLUDE_DIRS_OPENTRACING-CPP})
find_library(OPENTRACING_LIBRARY NAMES ${CONAN_LIBS_OPENTRACING-CPP} PATHS ${CONAN_LIB_DIRS_OPENTRACING-CPP})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(OPENTRACING DEFAULT_MSG OPENTRACING_INCLUDE_DIR OPENTRACING_LIBRARY)

if(OPENTRACING_FOUND)
    set(OPENTRACING_LIBRARIES ${OPENTRACING_LIBRARY})
    set(OPENTRACING_INCLUDE_DIRS ${OPENTRACING_INCLUDE_DIR})
endif()
