# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='vmware.concord.client.event.v1',
  syntax='proto3',
  serialized_options=b'\n\"com.vmware.concord.client.event.v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x65vent.proto\x12\x1evmware.concord.client.event.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n\x10SubscribeRequest\x12?\n\x06\x65vents\x18\x01 \x01(\x0b\x32-.vmware.concord.client.event.v1.EventsRequestH\x00\x12J\n\x0c\x65vent_groups\x18\x02 \x01(\x0b\x32\x32.vmware.concord.client.event.v1.EventGroupsRequestH\x00\x42\t\n\x07request\"\x9c\x01\n\x11SubscribeResponse\x12\x38\n\x06\x65vents\x18\x01 \x01(\x0b\x32&.vmware.concord.client.event.v1.EventsH\x00\x12\x41\n\x0b\x65vent_group\x18\x02 \x01(\x0b\x32*.vmware.concord.client.event.v1.EventGroupH\x00\x42\n\n\x08response\",\n\x12\x45ventGroupsRequest\x12\x16\n\x0e\x65vent_group_id\x18\x01 \x01(\x04\"\xe3\x01\n\nEventGroup\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06\x65vents\x18\x02 \x03(\x0c\x12/\n\x0brecord_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12S\n\rtrace_context\x18\x04 \x03(\x0b\x32<.vmware.concord.client.event.v1.EventGroup.TraceContextEntry\x1a\x33\n\x11TraceContextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\rEventsRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x04\"/\n\x05\x45vent\x12\x11\n\tevent_key\x18\x01 \x01(\x0c\x12\x13\n\x0b\x65vent_value\x18\x02 \x01(\x0c\"\xef\x01\n\x06\x45vents\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x04\x12\x35\n\x06\x65vents\x18\x02 \x03(\x0b\x32%.vmware.concord.client.event.v1.Event\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\x12O\n\rtrace_context\x18\x04 \x03(\x0b\x32\x38.vmware.concord.client.event.v1.Events.TraceContextEntry\x1a\x33\n\x11TraceContextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x82\x01\n\x0c\x45ventService\x12r\n\tSubscribe\x12\x30.vmware.concord.client.event.v1.SubscribeRequest\x1a\x31.vmware.concord.client.event.v1.SubscribeResponse0\x01\x42$\n\"com.vmware.concord.client.event.v1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='vmware.concord.client.event.v1.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='vmware.concord.client.event.v1.SubscribeRequest.events', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_groups', full_name='vmware.concord.client.event.v1.SubscribeRequest.event_groups', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='vmware.concord.client.event.v1.SubscribeRequest.request',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=81,
  serialized_end=251,
)


_SUBSCRIBERESPONSE = _descriptor.Descriptor(
  name='SubscribeResponse',
  full_name='vmware.concord.client.event.v1.SubscribeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='vmware.concord.client.event.v1.SubscribeResponse.events', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_group', full_name='vmware.concord.client.event.v1.SubscribeResponse.event_group', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='vmware.concord.client.event.v1.SubscribeResponse.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=254,
  serialized_end=410,
)


_EVENTGROUPSREQUEST = _descriptor.Descriptor(
  name='EventGroupsRequest',
  full_name='vmware.concord.client.event.v1.EventGroupsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_group_id', full_name='vmware.concord.client.event.v1.EventGroupsRequest.event_group_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=456,
)


_EVENTGROUP_TRACECONTEXTENTRY = _descriptor.Descriptor(
  name='TraceContextEntry',
  full_name='vmware.concord.client.event.v1.EventGroup.TraceContextEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='vmware.concord.client.event.v1.EventGroup.TraceContextEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='vmware.concord.client.event.v1.EventGroup.TraceContextEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=635,
  serialized_end=686,
)

_EVENTGROUP = _descriptor.Descriptor(
  name='EventGroup',
  full_name='vmware.concord.client.event.v1.EventGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='vmware.concord.client.event.v1.EventGroup.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='events', full_name='vmware.concord.client.event.v1.EventGroup.events', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='record_time', full_name='vmware.concord.client.event.v1.EventGroup.record_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trace_context', full_name='vmware.concord.client.event.v1.EventGroup.trace_context', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EVENTGROUP_TRACECONTEXTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=686,
)


_EVENTSREQUEST = _descriptor.Descriptor(
  name='EventsRequest',
  full_name='vmware.concord.client.event.v1.EventsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='vmware.concord.client.event.v1.EventsRequest.block_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=688,
  serialized_end=721,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='vmware.concord.client.event.v1.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_key', full_name='vmware.concord.client.event.v1.Event.event_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_value', full_name='vmware.concord.client.event.v1.Event.event_value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=723,
  serialized_end=770,
)


_EVENTS_TRACECONTEXTENTRY = _descriptor.Descriptor(
  name='TraceContextEntry',
  full_name='vmware.concord.client.event.v1.Events.TraceContextEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='vmware.concord.client.event.v1.Events.TraceContextEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='vmware.concord.client.event.v1.Events.TraceContextEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=635,
  serialized_end=686,
)

_EVENTS = _descriptor.Descriptor(
  name='Events',
  full_name='vmware.concord.client.event.v1.Events',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='vmware.concord.client.event.v1.Events.block_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='events', full_name='vmware.concord.client.event.v1.Events.events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='vmware.concord.client.event.v1.Events.correlation_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trace_context', full_name='vmware.concord.client.event.v1.Events.trace_context', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EVENTS_TRACECONTEXTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=773,
  serialized_end=1012,
)

_SUBSCRIBEREQUEST.fields_by_name['events'].message_type = _EVENTSREQUEST
_SUBSCRIBEREQUEST.fields_by_name['event_groups'].message_type = _EVENTGROUPSREQUEST
_SUBSCRIBEREQUEST.oneofs_by_name['request'].fields.append(
  _SUBSCRIBEREQUEST.fields_by_name['events'])
_SUBSCRIBEREQUEST.fields_by_name['events'].containing_oneof = _SUBSCRIBEREQUEST.oneofs_by_name['request']
_SUBSCRIBEREQUEST.oneofs_by_name['request'].fields.append(
  _SUBSCRIBEREQUEST.fields_by_name['event_groups'])
_SUBSCRIBEREQUEST.fields_by_name['event_groups'].containing_oneof = _SUBSCRIBEREQUEST.oneofs_by_name['request']
_SUBSCRIBERESPONSE.fields_by_name['events'].message_type = _EVENTS
_SUBSCRIBERESPONSE.fields_by_name['event_group'].message_type = _EVENTGROUP
_SUBSCRIBERESPONSE.oneofs_by_name['response'].fields.append(
  _SUBSCRIBERESPONSE.fields_by_name['events'])
_SUBSCRIBERESPONSE.fields_by_name['events'].containing_oneof = _SUBSCRIBERESPONSE.oneofs_by_name['response']
_SUBSCRIBERESPONSE.oneofs_by_name['response'].fields.append(
  _SUBSCRIBERESPONSE.fields_by_name['event_group'])
_SUBSCRIBERESPONSE.fields_by_name['event_group'].containing_oneof = _SUBSCRIBERESPONSE.oneofs_by_name['response']
_EVENTGROUP_TRACECONTEXTENTRY.containing_type = _EVENTGROUP
_EVENTGROUP.fields_by_name['record_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_EVENTGROUP.fields_by_name['trace_context'].message_type = _EVENTGROUP_TRACECONTEXTENTRY
_EVENTS_TRACECONTEXTENTRY.containing_type = _EVENTS
_EVENTS.fields_by_name['events'].message_type = _EVENT
_EVENTS.fields_by_name['trace_context'].message_type = _EVENTS_TRACECONTEXTENTRY
DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['SubscribeResponse'] = _SUBSCRIBERESPONSE
DESCRIPTOR.message_types_by_name['EventGroupsRequest'] = _EVENTGROUPSREQUEST
DESCRIPTOR.message_types_by_name['EventGroup'] = _EVENTGROUP
DESCRIPTOR.message_types_by_name['EventsRequest'] = _EVENTSREQUEST
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Events'] = _EVENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.event.v1.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

SubscribeResponse = _reflection.GeneratedProtocolMessageType('SubscribeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBERESPONSE,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.event.v1.SubscribeResponse)
  })
_sym_db.RegisterMessage(SubscribeResponse)

EventGroupsRequest = _reflection.GeneratedProtocolMessageType('EventGroupsRequest', (_message.Message,), {
  'DESCRIPTOR' : _EVENTGROUPSREQUEST,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.event.v1.EventGroupsRequest)
  })
_sym_db.RegisterMessage(EventGroupsRequest)

EventGroup = _reflection.GeneratedProtocolMessageType('EventGroup', (_message.Message,), {

  'TraceContextEntry' : _reflection.GeneratedProtocolMessageType('TraceContextEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENTGROUP_TRACECONTEXTENTRY,
    '__module__' : 'event_pb2'
    # @@protoc_insertion_point(class_scope:vmware.concord.client.event.v1.EventGroup.TraceContextEntry)
    })
  ,
  'DESCRIPTOR' : _EVENTGROUP,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.event.v1.EventGroup)
  })
_sym_db.RegisterMessage(EventGroup)
_sym_db.RegisterMessage(EventGroup.TraceContextEntry)

EventsRequest = _reflection.GeneratedProtocolMessageType('EventsRequest', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSREQUEST,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.event.v1.EventsRequest)
  })
_sym_db.RegisterMessage(EventsRequest)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.event.v1.Event)
  })
_sym_db.RegisterMessage(Event)

Events = _reflection.GeneratedProtocolMessageType('Events', (_message.Message,), {

  'TraceContextEntry' : _reflection.GeneratedProtocolMessageType('TraceContextEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENTS_TRACECONTEXTENTRY,
    '__module__' : 'event_pb2'
    # @@protoc_insertion_point(class_scope:vmware.concord.client.event.v1.Events.TraceContextEntry)
    })
  ,
  'DESCRIPTOR' : _EVENTS,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.event.v1.Events)
  })
_sym_db.RegisterMessage(Events)
_sym_db.RegisterMessage(Events.TraceContextEntry)


DESCRIPTOR._options = None
_EVENTGROUP_TRACECONTEXTENTRY._options = None
_EVENTS_TRACECONTEXTENTRY._options = None

_EVENTSERVICE = _descriptor.ServiceDescriptor(
  name='EventService',
  full_name='vmware.concord.client.event.v1.EventService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=1015,
  serialized_end=1145,
  methods=[
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='vmware.concord.client.event.v1.EventService.Subscribe',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_SUBSCRIBERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTSERVICE)

DESCRIPTOR.services_by_name['EventService'] = _EVENTSERVICE

# @@protoc_insertion_point(module_scope)
