# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='request.proto',
  package='vmware.concord.client.request.v1',
  syntax='proto3',
  serialized_options=b'\n$com.vmware.concord.client.request.v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rrequest.proto\x12 vmware.concord.client.request.v1\x1a\x1egoogle/protobuf/duration.proto\"\xc6\x01\n\x07Request\x12\x0f\n\x07request\x18\x01 \x01(\x0c\x12*\n\x07timeout\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x16\n\tread_only\x18\x03 \x01(\x08H\x00\x88\x01\x01\x12\x18\n\x0bpre_execute\x18\x04 \x01(\x08H\x01\x88\x01\x01\x12\x1b\n\x0e\x63orrelation_id\x18\x05 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_read_onlyB\x0e\n\x0c_pre_executeB\x11\n\x0f_correlation_id\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\x0c\x32o\n\x0eRequestService\x12]\n\x04Send\x12).vmware.concord.client.request.v1.Request\x1a*.vmware.concord.client.request.v1.ResponseB&\n$com.vmware.concord.client.request.v1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='vmware.concord.client.request.v1.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='vmware.concord.client.request.v1.Request.request', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='vmware.concord.client.request.v1.Request.timeout', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_only', full_name='vmware.concord.client.request.v1.Request.read_only', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pre_execute', full_name='vmware.concord.client.request.v1.Request.pre_execute', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='vmware.concord.client.request.v1.Request.correlation_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_read_only', full_name='vmware.concord.client.request.v1.Request._read_only',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_pre_execute', full_name='vmware.concord.client.request.v1.Request._pre_execute',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_correlation_id', full_name='vmware.concord.client.request.v1.Request._correlation_id',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=84,
  serialized_end=282,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='vmware.concord.client.request.v1.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='vmware.concord.client.request.v1.Response.response', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=312,
)

_REQUEST.fields_by_name['timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_REQUEST.oneofs_by_name['_read_only'].fields.append(
  _REQUEST.fields_by_name['read_only'])
_REQUEST.fields_by_name['read_only'].containing_oneof = _REQUEST.oneofs_by_name['_read_only']
_REQUEST.oneofs_by_name['_pre_execute'].fields.append(
  _REQUEST.fields_by_name['pre_execute'])
_REQUEST.fields_by_name['pre_execute'].containing_oneof = _REQUEST.oneofs_by_name['_pre_execute']
_REQUEST.oneofs_by_name['_correlation_id'].fields.append(
  _REQUEST.fields_by_name['correlation_id'])
_REQUEST.fields_by_name['correlation_id'].containing_oneof = _REQUEST.oneofs_by_name['_correlation_id']
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.request.v1.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.request.v1.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_REQUESTSERVICE = _descriptor.ServiceDescriptor(
  name='RequestService',
  full_name='vmware.concord.client.request.v1.RequestService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=314,
  serialized_end=425,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='vmware.concord.client.request.v1.RequestService.Send',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REQUESTSERVICE)

DESCRIPTOR.services_by_name['RequestService'] = _REQUESTSERVICE

# @@protoc_insertion_point(module_scope)
