# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_snapshot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='state_snapshot.proto',
  package='vmware.concord.client.statesnapshot.v1',
  syntax='proto3',
  serialized_options=b'\n*com.vmware.concord.client.statesnapshot.v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14state_snapshot.proto\x12&vmware.concord.client.statesnapshot.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1a\n\x18GetRecentSnapshotRequest\"\xbd\x01\n\x19GetRecentSnapshotResponse\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\x04\x12\x18\n\x0e\x65vent_group_id\x18\x02 \x01(\x04H\x00\x12\x12\n\x08\x62lock_id\x18\x03 \x01(\x04H\x00\x12 \n\x18key_value_count_estimate\x18\x04 \x01(\x04\x12/\n\x0bledger_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\n\n\x08taken_at\"b\n\x15StreamSnapshotRequest\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\x04\x12\x1e\n\x11last_received_key\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\x14\n\x12_last_received_key\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"a\n\x16StreamSnapshotResponse\x12G\n\tkey_value\x18\x01 \x01(\x0b\x32\x34.vmware.concord.client.statesnapshot.v1.KeyValuePair\"4\n\x0fReadAsOfRequest\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\x04\x12\x0c\n\x04keys\x18\x02 \x03(\x0c\"-\n\rOptionalValue\x12\x12\n\x05value\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x42\x08\n\x06_value\"Y\n\x10ReadAsOfResponse\x12\x45\n\x06values\x18\x01 \x03(\x0b\x32\x35.vmware.concord.client.statesnapshot.v1.OptionalValue2\xc4\x03\n\x14StateSnapshotService\x12\x98\x01\n\x11GetRecentSnapshot\x12@.vmware.concord.client.statesnapshot.v1.GetRecentSnapshotRequest\x1a\x41.vmware.concord.client.statesnapshot.v1.GetRecentSnapshotResponse\x12\x91\x01\n\x0eStreamSnapshot\x12=.vmware.concord.client.statesnapshot.v1.StreamSnapshotRequest\x1a>.vmware.concord.client.statesnapshot.v1.StreamSnapshotResponse0\x01\x12}\n\x08ReadAsOf\x12\x37.vmware.concord.client.statesnapshot.v1.ReadAsOfRequest\x1a\x38.vmware.concord.client.statesnapshot.v1.ReadAsOfResponseB,\n*com.vmware.concord.client.statesnapshot.v1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_GETRECENTSNAPSHOTREQUEST = _descriptor.Descriptor(
  name='GetRecentSnapshotRequest',
  full_name='vmware.concord.client.statesnapshot.v1.GetRecentSnapshotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=123,
)


_GETRECENTSNAPSHOTRESPONSE = _descriptor.Descriptor(
  name='GetRecentSnapshotResponse',
  full_name='vmware.concord.client.statesnapshot.v1.GetRecentSnapshotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='vmware.concord.client.statesnapshot.v1.GetRecentSnapshotResponse.snapshot_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_group_id', full_name='vmware.concord.client.statesnapshot.v1.GetRecentSnapshotResponse.event_group_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_id', full_name='vmware.concord.client.statesnapshot.v1.GetRecentSnapshotResponse.block_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value_count_estimate', full_name='vmware.concord.client.statesnapshot.v1.GetRecentSnapshotResponse.key_value_count_estimate', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ledger_time', full_name='vmware.concord.client.statesnapshot.v1.GetRecentSnapshotResponse.ledger_time', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='taken_at', full_name='vmware.concord.client.statesnapshot.v1.GetRecentSnapshotResponse.taken_at',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=126,
  serialized_end=315,
)


_STREAMSNAPSHOTREQUEST = _descriptor.Descriptor(
  name='StreamSnapshotRequest',
  full_name='vmware.concord.client.statesnapshot.v1.StreamSnapshotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='vmware.concord.client.statesnapshot.v1.StreamSnapshotRequest.snapshot_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_received_key', full_name='vmware.concord.client.statesnapshot.v1.StreamSnapshotRequest.last_received_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_last_received_key', full_name='vmware.concord.client.statesnapshot.v1.StreamSnapshotRequest._last_received_key',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=317,
  serialized_end=415,
)


_KEYVALUEPAIR = _descriptor.Descriptor(
  name='KeyValuePair',
  full_name='vmware.concord.client.statesnapshot.v1.KeyValuePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='vmware.concord.client.statesnapshot.v1.KeyValuePair.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='vmware.concord.client.statesnapshot.v1.KeyValuePair.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=459,
)


_STREAMSNAPSHOTRESPONSE = _descriptor.Descriptor(
  name='StreamSnapshotResponse',
  full_name='vmware.concord.client.statesnapshot.v1.StreamSnapshotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_value', full_name='vmware.concord.client.statesnapshot.v1.StreamSnapshotResponse.key_value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=558,
)


_READASOFREQUEST = _descriptor.Descriptor(
  name='ReadAsOfRequest',
  full_name='vmware.concord.client.statesnapshot.v1.ReadAsOfRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='vmware.concord.client.statesnapshot.v1.ReadAsOfRequest.snapshot_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keys', full_name='vmware.concord.client.statesnapshot.v1.ReadAsOfRequest.keys', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=612,
)


_OPTIONALVALUE = _descriptor.Descriptor(
  name='OptionalValue',
  full_name='vmware.concord.client.statesnapshot.v1.OptionalValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='vmware.concord.client.statesnapshot.v1.OptionalValue.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_value', full_name='vmware.concord.client.statesnapshot.v1.OptionalValue._value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=614,
  serialized_end=659,
)


_READASOFRESPONSE = _descriptor.Descriptor(
  name='ReadAsOfResponse',
  full_name='vmware.concord.client.statesnapshot.v1.ReadAsOfResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='vmware.concord.client.statesnapshot.v1.ReadAsOfResponse.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=750,
)

_GETRECENTSNAPSHOTRESPONSE.fields_by_name['ledger_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETRECENTSNAPSHOTRESPONSE.oneofs_by_name['taken_at'].fields.append(
  _GETRECENTSNAPSHOTRESPONSE.fields_by_name['event_group_id'])
_GETRECENTSNAPSHOTRESPONSE.fields_by_name['event_group_id'].containing_oneof = _GETRECENTSNAPSHOTRESPONSE.oneofs_by_name['taken_at']
_GETRECENTSNAPSHOTRESPONSE.oneofs_by_name['taken_at'].fields.append(
  _GETRECENTSNAPSHOTRESPONSE.fields_by_name['block_id'])
_GETRECENTSNAPSHOTRESPONSE.fields_by_name['block_id'].containing_oneof = _GETRECENTSNAPSHOTRESPONSE.oneofs_by_name['taken_at']
_STREAMSNAPSHOTREQUEST.oneofs_by_name['_last_received_key'].fields.append(
  _STREAMSNAPSHOTREQUEST.fields_by_name['last_received_key'])
_STREAMSNAPSHOTREQUEST.fields_by_name['last_received_key'].containing_oneof = _STREAMSNAPSHOTREQUEST.oneofs_by_name['_last_received_key']
_STREAMSNAPSHOTRESPONSE.fields_by_name['key_value'].message_type = _KEYVALUEPAIR
_OPTIONALVALUE.oneofs_by_name['_value'].fields.append(
  _OPTIONALVALUE.fields_by_name['value'])
_OPTIONALVALUE.fields_by_name['value'].containing_oneof = _OPTIONALVALUE.oneofs_by_name['_value']
_READASOFRESPONSE.fields_by_name['values'].message_type = _OPTIONALVALUE
DESCRIPTOR.message_types_by_name['GetRecentSnapshotRequest'] = _GETRECENTSNAPSHOTREQUEST
DESCRIPTOR.message_types_by_name['GetRecentSnapshotResponse'] = _GETRECENTSNAPSHOTRESPONSE
DESCRIPTOR.message_types_by_name['StreamSnapshotRequest'] = _STREAMSNAPSHOTREQUEST
DESCRIPTOR.message_types_by_name['KeyValuePair'] = _KEYVALUEPAIR
DESCRIPTOR.message_types_by_name['StreamSnapshotResponse'] = _STREAMSNAPSHOTRESPONSE
DESCRIPTOR.message_types_by_name['ReadAsOfRequest'] = _READASOFREQUEST
DESCRIPTOR.message_types_by_name['OptionalValue'] = _OPTIONALVALUE
DESCRIPTOR.message_types_by_name['ReadAsOfResponse'] = _READASOFRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetRecentSnapshotRequest = _reflection.GeneratedProtocolMessageType('GetRecentSnapshotRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETRECENTSNAPSHOTREQUEST,
  '__module__' : 'state_snapshot_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.statesnapshot.v1.GetRecentSnapshotRequest)
  })
_sym_db.RegisterMessage(GetRecentSnapshotRequest)

GetRecentSnapshotResponse = _reflection.GeneratedProtocolMessageType('GetRecentSnapshotResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRECENTSNAPSHOTRESPONSE,
  '__module__' : 'state_snapshot_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.statesnapshot.v1.GetRecentSnapshotResponse)
  })
_sym_db.RegisterMessage(GetRecentSnapshotResponse)

StreamSnapshotRequest = _reflection.GeneratedProtocolMessageType('StreamSnapshotRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMSNAPSHOTREQUEST,
  '__module__' : 'state_snapshot_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.statesnapshot.v1.StreamSnapshotRequest)
  })
_sym_db.RegisterMessage(StreamSnapshotRequest)

KeyValuePair = _reflection.GeneratedProtocolMessageType('KeyValuePair', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUEPAIR,
  '__module__' : 'state_snapshot_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.statesnapshot.v1.KeyValuePair)
  })
_sym_db.RegisterMessage(KeyValuePair)

StreamSnapshotResponse = _reflection.GeneratedProtocolMessageType('StreamSnapshotResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMSNAPSHOTRESPONSE,
  '__module__' : 'state_snapshot_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.statesnapshot.v1.StreamSnapshotResponse)
  })
_sym_db.RegisterMessage(StreamSnapshotResponse)

ReadAsOfRequest = _reflection.GeneratedProtocolMessageType('ReadAsOfRequest', (_message.Message,), {
  'DESCRIPTOR' : _READASOFREQUEST,
  '__module__' : 'state_snapshot_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.statesnapshot.v1.ReadAsOfRequest)
  })
_sym_db.RegisterMessage(ReadAsOfRequest)

OptionalValue = _reflection.GeneratedProtocolMessageType('OptionalValue', (_message.Message,), {
  'DESCRIPTOR' : _OPTIONALVALUE,
  '__module__' : 'state_snapshot_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.statesnapshot.v1.OptionalValue)
  })
_sym_db.RegisterMessage(OptionalValue)

ReadAsOfResponse = _reflection.GeneratedProtocolMessageType('ReadAsOfResponse', (_message.Message,), {
  'DESCRIPTOR' : _READASOFRESPONSE,
  '__module__' : 'state_snapshot_pb2'
  # @@protoc_insertion_point(class_scope:vmware.concord.client.statesnapshot.v1.ReadAsOfResponse)
  })
_sym_db.RegisterMessage(ReadAsOfResponse)


DESCRIPTOR._options = None

_STATESNAPSHOTSERVICE = _descriptor.ServiceDescriptor(
  name='StateSnapshotService',
  full_name='vmware.concord.client.statesnapshot.v1.StateSnapshotService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=753,
  serialized_end=1205,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRecentSnapshot',
    full_name='vmware.concord.client.statesnapshot.v1.StateSnapshotService.GetRecentSnapshot',
    index=0,
    containing_service=None,
    input_type=_GETRECENTSNAPSHOTREQUEST,
    output_type=_GETRECENTSNAPSHOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamSnapshot',
    full_name='vmware.concord.client.statesnapshot.v1.StateSnapshotService.StreamSnapshot',
    index=1,
    containing_service=None,
    input_type=_STREAMSNAPSHOTREQUEST,
    output_type=_STREAMSNAPSHOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadAsOf',
    full_name='vmware.concord.client.statesnapshot.v1.StateSnapshotService.ReadAsOf',
    index=2,
    containing_service=None,
    input_type=_READASOFREQUEST,
    output_type=_READASOFRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATESNAPSHOTSERVICE)

DESCRIPTOR.services_by_name['StateSnapshotService'] = _STATESNAPSHOTSERVICE

# @@protoc_insertion_point(module_scope)
