#!/usr/bin/env python3

import socket
import sys
import os

port = 6888
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("127.0.0.1", port))
cmd = b' '.join([os.fsencode(arg) for arg in sys.argv[1:]]) + b'\n'
s.send(cmd)
data = s.recv(64*1024)
print(data.decode())
