#!/usr/bin/env python

import socket
import sys

port = 6888
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("127.0.0.1", port))
cmd = b' '.join(sys.argv[1:]) + b'\n'
s.send(cmd)
data = s.recv(64*1024)
print(data.decode())
f = open("status.txt", "w")
f.write(data.decode())
f.close()