name: Release build (gcc)
on:
  schedule:
    - cron: "0 12 * * 6" # Every Saturday at 12PM UTC

jobs:
  build:
    name: dummy
    runs-on: ubuntu-18.04
    strategy:
        fail-fast: false
    steps:
        - name: dummy
          run: |
            echo "done"