name: Debug build (clang)
on: [push, pull_request]

jobs:
  build:
    name: dummy
    runs-on: ubuntu-18.04
    strategy:
        fail-fast: false
    steps:
        - name: Cleanup pre-installed tools
          run: |
            echo "done"