name: tsan
on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:
    name: dummy
    runs-on: ubuntu-18.04
    strategy:
        fail-fast: false
    steps:
        - name: dummy
          run: |
            echo "done"